<script lang="ts">
	// import ui components
	import * as Dialog from '$lib/components/ui/dialog/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import * as Accordion from '$lib/components/ui/accordion/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as ToggleGroup from '$lib/components/ui/toggle-group/index.js';

	// import lucide icons
	import HashIcon from '@lucide/svelte/icons/hash';
	import UserIcon from '@lucide/svelte/icons/user';
	import UserCheckIcon from '@lucide/svelte/icons/user-check';
	import WrenchIcon from '@lucide/svelte/icons/wrench';
	import BotIcon from '@lucide/svelte/icons/bot';
	import BotOffIcon from '@lucide/svelte/icons/bot-off';
	import ThumbsUpIcon from '@lucide/svelte/icons/thumbs-up';
	import ThumbsDownIcon from '@lucide/svelte/icons/thumbs-down';
	import LoaderIcon from '@lucide/svelte/icons/loader';
	import TriangleAlertIcon from '@lucide/svelte/icons/triangle-alert';

	// import svelte features
	import { onMount } from 'svelte';

	// import svelte stores
	import { page } from '$app/state';

	let {
		id = '',
		botResponse = '',
		channel = '',
		createdAt = new Date(),
		realUserMessage = false,
		triggeredTask = '0',
		userMessage = '',
		taskHistoryId = '',
		edits = [],
		tasks = {},
		testCaseBadge = false,
		checkingBadge = false
	} = $props();

	let loadingBotResponse = $state(true);
	let botResponses = $state([]);
	let thumbsUp = $state([]);
	let thumbsDown = $state([]);

	const textLengthCap = 95;

	onMount(async () => {
		let data;
		if (page.url.pathname === '/cases') {
			const res = await fetch(`/api/cases/${id}/botResponses?taskHistoryId=${taskHistoryId}`, {
				method: 'GET',
				headers: {
					'Content-Type': 'application/json'
				}
			});
			if (!res.ok) {
				console.error(`Failed to fetch the latest bot response of case #${id}`, res.statusText);
				return;
			}
			data = await res.json();
		} else if (page.url.pathname.startsWith('/proposals/')) {
			const proposalId = page.params.proposalId;
			const res = await fetch(
				`/api/cases/${id}/botResponses?taskHistoryId=${taskHistoryId}&proposalId=${proposalId}`,
				{
					method: 'GET',
					headers: {
						'Content-Type': 'application/json'
					}
				}
			);
			if (!res.ok) {
				console.error(`Failed to fetch the latest bot response of case #${id}`, res.statusText);
				return;
			}
			data = await res.json();
		}
		botResponses = data.botResponses;
		loadingBotResponse = false;
	});
</script>

<Dialog.Root>
	<Dialog.Trigger class="hover:cursor-pointer">
		<Card.Root class="hover:bg-muted/50 h-full w-full text-left">
			<Card.Header>
				<!-- <Card.Title></Card.Title> -->
				<Card.Description class="flex justify-between">
					{#if checkingBadge}
						<Badge class="bg-discord-yellow text-black">worth checking</Badge>
					{/if}
					{#if testCaseBadge}
						<Badge>test case</Badge>
					{/if}
				</Card.Description>
			</Card.Header>
			<Card.Content>
				<div class="mb-2 flex items-center">
					<HashIcon class="mr-2 size-4" />
					<h4 class="font-medium">
						{channel.startsWith('#') ? channel.slice(1) : channel}
					</h4>
				</div>
				<div class="mb-4 flex">
					{#if realUserMessage}
						<UserCheckIcon class="mt-1 mr-2 size-4 flex-none" />
					{:else}
						<UserIcon class="mt-1 mr-2 size-4 flex-none" />
					{/if}
					<p>
						{#if userMessage.length <= textLengthCap}
							{userMessage}
						{:else}
							{userMessage.substring(0, textLengthCap)}...
						{/if}
					</p>
				</div>
				{#if loadingBotResponse}
					<div class="mb-2 flex items-center">
						<LoaderIcon class="mr-2 size-4 animate-spin" />
						<p>Loading bot response...</p>
					</div>
				{:else}
					{#if page.url.pathname === '/cases'}
						{#if botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
							{@const response = botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
							<div class="mb-2 flex items-center">
								<WrenchIcon class="mr-2 size-4" />
								<h4 class="font-medium">
									{response.triggeredTask in tasks
										? tasks[response.triggeredTask].name
										: 'No Task is Triggered'}
								</h4>
							</div>
							<div class=" flex">
								{#if response.botResponse !== ''}
									<BotIcon class="mt-1 mr-2 size-4 flex-none" />
									<p>{response.botResponse}</p>
								{:else if response.botResponse === '' && response.triggeredTask !== '0'}
									<BotOffIcon class="mt-1 mr-2 size-4 flex-none" />
									<p>The bot chose not to respond.</p>
								{/if}
							</div>
						{:else}
							<p>No response has been generated by the most recent version of the bot.</p>
						{/if}
					{/if}
					{#if page.url.pathname.startsWith('/proposals/')}
						{#if edits.length > 0}
							{#if botResponses.find((r) => r.proposalEditId === edits[0].id)}
								{@const response = botResponses.find((r) => r.proposalEditId === edits[0].id)}
								<div class="mb-2 flex items-center">
									<WrenchIcon class="mr-2 size-4" />
									<h4 class="font-medium">
										{response.triggeredTask in tasks
											? tasks[response.triggeredTask].name
											: 'No Task is Triggered'}
									</h4>
								</div>
								<div class=" flex">
									{#if response.botResponse !== ''}
										<BotIcon class="mt-1 mr-2 size-4 flex-none" />
										<p>{response.botResponse}</p>
									{:else if response.botResponse === '' && response.triggeredTask !== '0'}
										<BotOffIcon class="mt-1 mr-2 size-4 flex-none" />
										<p>The bot chose not to respond.</p>
									{/if}
								</div>
							{:else}
								<p>No response has been generated by the most recent proposed edit to the bot.</p>
							{/if}
						{:else if botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
							{@const response = botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
							<div class="mb-2 flex items-center">
								<WrenchIcon class="mr-2 size-4" />
								<h4 class="font-medium">
									{response.triggeredTask in tasks
										? tasks[response.triggeredTask].name
										: 'No Task is Triggered'}
								</h4>
							</div>
							<div class=" flex">
								{#if response.botResponse !== ''}
									<BotIcon class="mt-1 mr-2 size-4 flex-none" />
									<p>{response.botResponse}</p>
								{:else if response.botResponse === '' && response.triggeredTask !== '0'}
									<BotOffIcon class="mt-1 mr-2 size-4 flex-none" />
									<p>The bot chose not to respond.</p>
								{/if}
							</div>
						{:else}
							<p>No response has been generated by the initial prompt.</p>
						{/if}
					{/if}
				{/if}
			</Card.Content>
			{#if !loadingBotResponse}
				<Card.Footer class="mt-auto">
					<div class="flex w-full items-center justify-around">
						<div class="flex items-center">
							<ThumbsUpIcon class="mr-2 size-5" />
							<p>{thumbsUp.length}</p>
						</div>
						<div class="flex items-center">
							<ThumbsDownIcon class="mr-2 size-5" />
							<p>{thumbsDown.length}</p>
						</div>
					</div>
				</Card.Footer>
			{/if}
		</Card.Root>
	</Dialog.Trigger>
	<Dialog.Content>
		<Dialog.Header>
			<Dialog.Title class="mb-2 flex gap-2">
				{#if checkingBadge}
					<Badge class="bg-discord-yellow text-black">worth checking</Badge>
				{/if}
				{#if testCaseBadge}
					<Badge>test case</Badge>
				{/if}
			</Dialog.Title>
			<Dialog.Description class="text-left">
				<div class="mb-2 flex items-center">
					<HashIcon class="mr-2 size-4" />
					<h4 class="font-medium">
						{channel.startsWith('#') ? channel.slice(1) : channel}
					</h4>
				</div>
				<div class="mb-4 flex">
					{#if realUserMessage}
						<UserCheckIcon class="mt-1 mr-2 size-4 flex-none" />
					{:else}
						<UserIcon class="mt-1 mr-2 size-4 flex-none" />
					{/if}
					<p>{userMessage}</p>
				</div>
				{#if loadingBotResponse}
					<div class="mb-2 flex items-center">
						<LoaderIcon class="mr-2 size-4 animate-spin" />
						<p>Loading bot response...</p>
					</div>
				{:else}
					{#if page.url.pathname === '/cases'}
						{#if botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
							{@const response = botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
							<div class="mb-2 flex items-center">
								<WrenchIcon class="mr-2 size-4" />
								<h4 class="font-medium">
									{response.triggeredTask in tasks
										? tasks[response.triggeredTask].name
										: 'No Task is Triggered'}
								</h4>
							</div>
							<div class=" flex">
								{#if response.botResponse !== ''}
									<BotIcon class="mt-1 mr-2 size-4 flex-none" />
									<p>{response.botResponse}</p>
								{:else if response.botResponse === '' && response.triggeredTask !== '0'}
									<BotOffIcon class="mt-1 mr-2 size-4 flex-none" />
									<p>The bot chose not to respond.</p>
								{/if}
							</div>
						{:else}
							<p>No response has been generated by the most recent version of the bot.</p>
						{/if}
					{/if}
					{#if page.url.pathname.startsWith('/proposals/')}
						{#if edits.length > 0}
							{#if botResponses.find((r) => r.proposalEditId === edits[0].id)}
								{@const response = botResponses.find((r) => r.proposalEditId === edits[0].id)}
								<div class="mb-2 flex items-center">
									<WrenchIcon class="mr-2 size-4" />
									<h4 class="font-medium">
										{response.triggeredTask in tasks
											? tasks[response.triggeredTask].name
											: 'No Task is Triggered'}
									</h4>
								</div>
								<div class=" flex">
									{#if response.botResponse !== ''}
										<BotIcon class="mt-1 mr-2 size-4 flex-none" />
										<p>{response.botResponse}</p>
									{:else if response.botResponse === '' && response.triggeredTask !== '0'}
										<BotOffIcon class="mt-1 mr-2 size-4 flex-none" />
										<p>The bot chose not to respond.</p>
									{/if}
								</div>
							{:else}
								<p>No response has been generated by the most recent proposed edit to the bot.</p>
							{/if}
						{:else if botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
							{@const response = botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
							<div class="mb-2 flex items-center">
								<WrenchIcon class="mr-2 size-4" />
								<h4 class="font-medium">
									{response.triggeredTask in tasks
										? tasks[response.triggeredTask].name
										: 'No Task is Triggered'}
								</h4>
							</div>
							<div class=" flex">
								{#if response.botResponse !== ''}
									<BotIcon class="mt-1 mr-2 size-4 flex-none" />
									<p>{response.botResponse}</p>
								{:else if response.botResponse === '' && response.triggeredTask !== '0'}
									<BotOffIcon class="mt-1 mr-2 size-4 flex-none" />
									<p>The bot chose not to respond.</p>
								{/if}
							</div>
						{:else}
							<p>No response has been generated by the initial prompt.</p>
						{/if}
					{/if}
				{/if}
				<ToggleGroup.Root type="single" class="my-6 w-full" variant="outline">
					<ToggleGroup.Item value="good">
						<ThumbsUpIcon class="size-4" />good response
					</ToggleGroup.Item>
					<ToggleGroup.Item value="bad">
						<ThumbsDownIcon class="size-4" />bad response
					</ToggleGroup.Item>
				</ToggleGroup.Root>
				{#if page.url.pathname.startsWith('/proposals/')}
					<h4>Bot responses from all edits and the initial prompt:</h4>
					<Accordion.Root type="single" class="w-full">
						{#each edits as edit, i (edit.id)}
							<Accordion.Item value="edit-{edit.id}">
								<Accordion.Trigger>
									{edit.editor}'s edit {#if i === 0}(current){/if}
								</Accordion.Trigger>
								<Accordion.Content class="flex flex-col gap-4 text-balance">
									{#if loadingBotResponse}
										<div class="mb-2 flex items-center">
											<LoaderIcon class="mr-2 size-4 animate-spin" />
											<p>Loading bot response...</p>
										</div>
									{:else if botResponses.find((r) => r.proposalEditId === edit.id)}
										{@const response = botResponses.find((r) => r.proposalEditId === edit.id)}
										<div class=" flex items-center">
											<WrenchIcon class="mr-2 size-4" />
											<h4 class="font-medium">
												{response.triggeredTask in tasks
													? tasks[response.triggeredTask].name
													: 'No Task is Triggered'}
											</h4>
										</div>
										<div class=" flex">
											{#if response.botResponse !== ''}
												<BotIcon class="mt-1 mr-2 size-4 flex-none" />
												<p>{response.botResponse}</p>
											{:else if response.botResponse === '' && response.triggeredTask !== '0'}
												<BotOffIcon class="mt-1 mr-2 size-4 flex-none" />
												<p>The bot chose not to respond.</p>
											{/if}
										</div>
									{:else}
										<p>No bot response has been generated from this edit.</p>
									{/if}
								</Accordion.Content>
							</Accordion.Item>
						{/each}
						<Accordion.Item value="task-{taskHistoryId}">
							<Accordion.Trigger>
								initial prompt {#if edits.length === 0}(current){/if}
							</Accordion.Trigger>
							<Accordion.Content class="flex flex-col gap-4 text-balance">
								{#if loadingBotResponse}
									<div class="mb-2 flex items-center">
										<LoaderIcon class="mr-2 size-4 animate-spin" />
										<p>Loading bot response...</p>
									</div>
								{:else if botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
									{@const response = botResponses.find((r) => r.taskHistoryId === taskHistoryId)}
									<div class=" flex items-center">
										<WrenchIcon class="mr-2 size-4" />
										<h4 class="font-medium">
											{response.triggeredTask in tasks
												? tasks[response.triggeredTask].name
												: 'No Task is Triggered'}
										</h4>
									</div>
									<div class=" flex">
										{#if response.botResponse !== ''}
											<BotIcon class="mt-1 mr-2 size-4 flex-none" />
											<p>{response.botResponse}</p>
										{:else if response.botResponse === '' && response.triggeredTask !== '0'}
											<BotOffIcon class="mt-1 mr-2 size-4 flex-none" />
											<p>The bot chose not to respond.</p>
										{/if}
									</div>
								{:else}
									<p>No bot response has been generated from this prompt.</p>
								{/if}
							</Accordion.Content>
						</Accordion.Item>
					</Accordion.Root>
					<Button variant="secondary" class="mt-4 w-full">
						<TriangleAlertIcon class="size-4" />
						remove this case from the test suite
					</Button>
				{/if}
				<!-- <p class="mx-auto mt-2">Case ID: {id}</p> -->
			</Dialog.Description>
		</Dialog.Header>
	</Dialog.Content>
</Dialog.Root>
